import type { AuctionConfig } from './types'

export const TOTAL_ROUNDS = 10

export const AUCTION_CONFIGS: AuctionConfig[] = [
  {
    key: 'first-2',
    title: 'First Price Sealed Bid — 2 Bidders',
    shortTitle: 'First Price · 2-Bidder',
    bidders: 2,
    entryFee: null,
    reservePrice: null,
    nashDescription: 'Nash equilibrium: bid v/2',
    nashSlope: 0.5,
    participationThreshold: null,
    nashFormula: (v) => v / 2,
  },
  {
    key: 'first-5',
    title: 'First Price Sealed Bid — 5 Bidders',
    shortTitle: 'First Price · 5-Bidder',
    bidders: 5,
    entryFee: null,
    reservePrice: null,
    nashDescription: 'Nash equilibrium: bid 4v/5',
    nashSlope: 0.8,
    participationThreshold: null,
    nashFormula: (v) => (4 * v) / 5,
  },
  {
    key: 'second-2',
    title: 'Second Price Sealed Bid — 2 Bidders',
    shortTitle: 'Second Price · 2-Bidder',
    bidders: 2,
    entryFee: null,
    reservePrice: null,
    nashDescription: 'Dominant strategy: bid your true value',
    nashSlope: 1.0,
    participationThreshold: null,
    nashFormula: (v) => v,
  },
  {
    key: 'second-5',
    title: 'Second Price Sealed Bid — 5 Bidders',
    shortTitle: 'Second Price · 5-Bidder',
    bidders: 5,
    entryFee: null,
    reservePrice: null,
    nashDescription: 'Dominant strategy: bid your true value',
    nashSlope: 1.0,
    participationThreshold: null,
    nashFormula: (v) => v,
  },
  {
    key: 'first-2-entry25',
    title: 'First Price Sealed Bid — 2 Bidders, $25 Entry Fee',
    shortTitle: 'First Price · 2-Bidder · $25 Entry',
    bidders: 2,
    entryFee: 25,
    reservePrice: null,
    nashDescription: 'v > 50: bid v/2 − 1/(8v) · v ≤ 50: bid 0',
    nashSlope: null,
    participationThreshold: 50,
    nashFormula: (v) => (v > 50 ? v / 2 - 1 / (8 * v) : 0),
  },
  {
    key: 'first-2-reserve50',
    title: 'First Price Sealed Bid — 2 Bidders, $50 Reserve',
    shortTitle: 'First Price · 2-Bidder · $50 Reserve',
    bidders: 2,
    entryFee: null,
    reservePrice: 50,
    nashDescription: 'v > 50: bid v/2 + 1/(8v) · v ≤ 50: bid 0',
    nashSlope: null,
    participationThreshold: 50,
    nashFormula: (v) => (v > 50 ? v / 2 + 1 / (8 * v) : 0),
  },
  {
    key: 'second-2-entry25',
    title: 'Second Price Sealed Bid — 2 Bidders, $25 Entry Fee',
    shortTitle: 'Second Price · 2-Bidder · $25 Entry',
    bidders: 2,
    entryFee: 25,
    reservePrice: null,
    nashDescription: 'v > 50: bid v (truthful) · v ≤ 50: bid 0',
    nashSlope: null,
    participationThreshold: 50,
    nashFormula: (v) => (v > 50 ? v : 0),
  },
  {
    key: 'second-2-reserve50',
    title: 'Second Price Sealed Bid — 2 Bidders, $50 Reserve',
    shortTitle: 'Second Price · 2-Bidder · $50 Reserve',
    bidders: 2,
    entryFee: null,
    reservePrice: 50,
    nashDescription: 'v > 50: bid v (truthful) · v ≤ 50: bid 0',
    nashSlope: null,
    participationThreshold: 50,
    nashFormula: (v) => (v > 50 ? v : 0),
  },
]

export function getAuctionConfig(key: string): AuctionConfig | undefined {
  return AUCTION_CONFIGS.find((a) => a.key === key)
}
